[project]
name = "magnetsimulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniel Struck", email = "daniel.struck@gmx.net" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
]

[project.scripts]
magnetsimulation = "magnetsimulation:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
